apiVersion: 1

datasources:
  - name: Postgres-TimescaleDB
    type: postgres
    url: postgres:5432
    user: ${DB_USER}
    secureJsonData:
      password: ${DB_PASSWORD}
    jsonData:
      database: ${DB_NAME}
      sslmode: 'disable'
      postgresVersion: 1600
      timescaledb: true